### ISSUE TITLE
How to run code with my own file

### ISSUE THREAD

**Issue by 8banzhuan** [kedartatwawadi/stanford_compression_library#77]
like python .py inputfile outputfile

**Comment by shubhamchandak94** [comment]
You can also find examples of this in the lz77 code at https://github.com/kedartatwawadi/stanford_compression_library/blob/main/compressors/lz77.py#L690. 
You can run this like 
```
python lz77.py -i infile -o outfile 
```
for compression. For decompression you can do
```
python lz77.py -d -i infile -o outfile 
```

Note that the lz77 coder redefines the encode_file and decode_file functions to use binary file I/O instead of text-based (see [here](https://github.com/kedartatwawadi/stanford_compression_library/blob/main/compressors/lz77.py#L375) and [here](https://github.com/kedartatwawadi/stanford_compression_library/blob/main/compressors/lz77.py#L516).
